import type { BuffDef } from '@/core/types'
import { icon } from '../commons/icon-paths'

export const WHITE_MAGE_BUFFS: Record<string, BuffDef> = {
  whm_lily: {
    id: 'whm_lily',
    name: '治疗百合',
    description: '战斗中每 20 秒积攒 1 朵，最多 3 朵。狂喜之心消耗 1 朵。',
    icon: icon('skill_icons/24_WHM', 2643),
    type: 'buff',
    duration: 0,
    stackable: true,
    maxStacks: 3,
    preserveOnDeath: true,
    hidden: true,
    effects: [],
  },
  whm_blood_lily: {
    id: 'whm_blood_lily',
    name: '血百合',
    description: '狂喜之心有效治疗时积攒 1 朵，最多 3 朵。苦难之心消耗 3 朵。',
    icon: icon('skill_icons/24_WHM', 2644),
    type: 'buff',
    duration: 0,
    stackable: true,
    maxStacks: 3,
    preserveOnDeath: true,
    hidden: true,
    effects: [],
  },
  whm_medica_ii: {
    id: 'whm_medica_ii',
    name: '医济',
    description: '体力持续恢复。',
    icon: icon('player_skill_effects', 10413),
    type: 'buff',
    duration: 15000,
    stackable: false,
    maxStacks: 1,
    effects: [{ type: 'hot', potency: 0.5, interval: 3000 }],
  },
  whm_temperance: {
    id: 'whm_temperance',
    name: '节制',
    description: '受到的伤害降低 10%。',
    icon: icon('player_skill_effects', 12634),
    type: 'buff',
    duration: 20000,
    stackable: false,
    maxStacks: 1,
    effects: [{ type: 'mitigation', value: 0.1 }],
  },
  // Free Raise ↔ its recharge: spending one starts the other, so a free raise returns 180s after use
  whm_free_raise: {
    id: 'whm_free_raise',
    name: '免费复活',
    description: '下一次复活瞬发且不消耗 MP。使用后 180 秒重新获得。',
    // Healers instant-raise with Swiftcast in FFXIV; this is that, handed out on a timer
    icon: icon('player_skill_effects', 10454),
    type: 'buff',
    duration: 0,
    stackable: false,
    maxStacks: 1,
    preserveOnDeath: true,
    effects: [],
    onRemove: [{ type: 'apply_buff', buffId: 'whm_raise_recharge' }],
  },
  whm_raise_recharge: {
    id: 'whm_raise_recharge',
    name: '免费复活准备中',
    description: '结束时重新获得免费复活。',
    type: 'buff',
    duration: 180000,
    durationGrace: 0,
    stackable: false,
    maxStacks: 1,
    preserveOnDeath: true,
    hidden: true,
    effects: [],
    onRemove: [{ type: 'apply_buff', buffId: 'whm_free_raise' }],
  },
}
