import type { BuffDef } from '@/core/types'
import { icon } from '../commons/icon-paths'

export const PALADIN_BUFFS: Record<string, BuffDef> = {
  pld_requiescat: {
    id: 'pld_requiescat',
    name: '安魂祈祷',
    description: '释放圣灵时消耗1层使其即时咏唱。',
    icon: icon('player_skill_effects', 12514),
    type: 'buff',
    duration: 21000,
    stackable: true,
    maxStacks: 4,
    effects: [],
  },
  pld_fof: {
    id: 'pld_fof',
    name: '战逃反应',
    description: '释放先锋剑时消耗1层使其威力提高25%，并回复2000MP。',
    icon: icon('player_skill_effects', 10155),
    type: 'buff',
    duration: 21000,
    stackable: true,
    maxStacks: 4,
    effects: [],
  },
  pld_holy_sheltron: {
    id: 'pld_holy_sheltron',
    name: '圣盾阵',
    description: '受到的伤害降低 20%。',
    icon: icon('player_skill_effects', 12515),
    type: 'buff',
    duration: 8000,
    stackable: false,
    maxStacks: 1,
    effects: [{ type: 'mitigation', value: 0.2 }],
  },
  pld_sheltron_shield: {
    id: 'pld_sheltron_shield',
    name: '圣盾阵护盾',
    description: '抵消一定伤害的护盾。护盾被击破或时间结束时回复体力。',
    icon: icon('player_skill_effects', 12510),
    type: 'buff',
    duration: 8000,
    stackable: true,
    maxStacks: Infinity,
    shield: true,
    effects: [],
    onRemove: [{ type: 'heal', potency: 2.0 }],
  },
  pld_hallowed: {
    id: 'pld_hallowed',
    name: '神圣领域',
    description: '特殊攻击之外其他所有攻击均无效。',
    icon: icon('player_skill_effects', 12504),
    type: 'buff',
    duration: 10000,
    stackable: false,
    maxStacks: 1,
    effects: [{ type: 'invulnerable' }],
  },
}
